name: liveasy
description: Liveasy Transport

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.17.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  geolocator: ^7.0.3
  geocoding: ^2.0.1
  location_permissions: ^4.0.0
  provider: ^5.0.0
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^1.0.0
  flutter_spinkit: ^5.0.0
  get: ^4.3.8
  get_storage: ^2.0.3
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  pinput: ^1.2.0
  modal_progress_hud_alt: ^1.0.0
  social_share: ^2.1.1
  image_picker: ^0.8.4
  contacts_service: ^0.6.1
  fluttercontactpicker: ^4.5.1
  url_launcher: ^6.0.9
  firebase_dynamic_links: ^2.0.7
  wc_flutter_share: ^0.4.0
  date_format: ^2.0.2
  jiffy: ^4.1.0
  otp_text_field: ^1.1.1
  firebase_messaging: ^10.0.4
  overlay_support: ^1.2.1
  shimmer: ^2.0.0
  screenshot: ^1.2.3
  flutter_easyloading: ^3.0.0
  marquee: ^2.2.0
  permission_handler: ^8.1.4+2
  flutter_local_notifications: ^8.1.1+1
  onesignal_flutter: ^3.0.0

  package_info: ^2.0.2
  firebase_remote_config: ^0.10.0+4
  shared_preferences: ^2.0.6
  location: ^4.3.0
  device_info: ^2.0.2
  firebase_database: ^7.2.0
  flutter_background: ^1.0.2+1
  visibility_aware_state: ^1.0.3
  background_location: ^0.6.1
  fluster: ^1.2.0
  google_maps_cluster_manager: ^3.0.0+1
  flutter_cache_manager: ^3.1.2
  logger: ^1.1.0
  date_time_picker: ^2.1.0
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^2.2.0
  connectivity: ^3.0.6
  flutter_gifimage: ^1.0.0
  flutter_google_places: ^0.3.0
  custom_info_window: ^1.0.1
  share: ^2.0.4
  dotted_line: ^3.1.0
  flutter_animarker: ^3.2.0

dev_dependencies:
  flutter_config: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/navigationIcons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
